# Generated by Django 3.2.7 on 2021-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_donor_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PatientAge', models.IntegerField()),
                ('PatientBloodGroup', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('O+', 'O+')], max_length=70)),
                ('Unitsofbloodrequried', models.IntegerField()),
                ('PhoneNumber', models.BigIntegerField()),
                ('Email', models.EmailField(help_text='xyz@gmail.com', max_length=254, null=True)),
                ('HospitalName', models.CharField(max_length=90)),
                ('Address', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('Hyderabad', 'Hyderabad')], default='1', max_length=43)),
                ('Purpose', models.CharField(max_length=100)),
            ],
        ),
    ]
