# Generated by Django 3.2.7 on 2021-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_mdl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('fname', models.CharField(max_length=30, null=True)),
                ('blood_group', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('O+', 'O+')], max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=10, null=True)),
                ('date_brth', models.DateField(null=True)),
                ('email', models.EmailField(help_text='xyz@gmail.com', max_length=254, null=True)),
                ('address', models.CharField(help_text='Area', max_length=50, null=True)),
                ('city', models.CharField(choices=[('Hyderabad', 'Hyderabad')], default='Hyderabad', max_length=50)),
                ('phone_no', models.IntegerField()),
                ('LastDonateDate', models.DateField(null=True)),
                ('extra_info', models.CharField(max_length=50)),
            ],
        ),
    ]
